/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.43
 * Generated at: 2017-05-01 05:40:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class PropertyDelete_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Property Delete</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse navbar-fixed-top\"> <!-- Access-->\r\n");
      out.write("\t<div class=\"btn-group\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-primary\">Access</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-primary dropdown-toggle\"\r\n");
      out.write("\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t<span class=\"caret\"></span> <span class=\"sr-only\">Toggle\r\n");
      out.write("\t\t\t\tDropdown</span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t<li href = \"http://localhost:8080/br.usjt.oficial.project/AccessRead.jsp\"><a>Read</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/AccessCreate.jsp\">Insert</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/AccessUpdate.jsp\">Update</a></li>\r\n");
      out.write("\t\t\t<li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/AccessDelete.jsp\">Delete</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- AirConditioningTemperature-->\r\n");
      out.write("\t<div class=\"btn-group\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-primary\">AirConditioningTemperature</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-primary dropdown-toggle\"\r\n");
      out.write("\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t<span class=\"caret\"></span> <span class=\"sr-only\">Toggle\r\n");
      out.write("\t\t\t\tDropdown</span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/AirConditioningTemperatureCreate.jsp\">Read</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/AirConditioningTemperatureUpdate.jsp\">Update</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Company-->\r\n");
      out.write("\t<div class=\"btn-group\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-primary\">Company</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-primary dropdown-toggle\"\r\n");
      out.write("\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t<span class=\"caret\"></span> <span class=\"sr-only\">Toggle\r\n");
      out.write("\t\t\t\tDropdown</span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/CompanyRead.jsp\">Read</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/CompanyCreate.jsp\">Insert</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/CompanyUpdate.jsp\">Update</a></li>\r\n");
      out.write("\t\t\t<li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/CompanyDelete.jsp\">Delete</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- PropertySet-->\r\n");
      out.write("\t<div class=\"btn-group\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-primary\">PropertySet</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-primary dropdown-toggle\"\r\n");
      out.write("\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t<span class=\"caret\"></span> <span class=\"sr-only\">Toggle\r\n");
      out.write("\t\t\t\tDropdown</span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/PropertyRead.jsp\">Read</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/PropertySetJSP.jsp\">Insert</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/PropertyUpdate.jsp\">Update</a></li>\r\n");
      out.write("\t\t\t<li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/PropertyDelete.jsp\">Delete</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- User-->\r\n");
      out.write("\t<div class=\"btn-group\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-primary\">User</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-primary dropdown-toggle\"\r\n");
      out.write("\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t<span class=\"caret\"></span> <span class=\"sr-only\">Toggle\r\n");
      out.write("\t\t\t\tDropdown</span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/UserRead.jsp\">Read</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/UserJSP.jsp\">Insert</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/UserUpdate.jsp\">Update</a></li>\r\n");
      out.write("\t\t\t<li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/br.usjt.oficial.project/UserDelete.jsp\">Delete</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"nav navbar-nav navbar-right\"> <!-- Login-->\r\n");
      out.write("\t<div class=\"btn-group\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-primary\">Adm</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-lg btn-primary dropdown-toggle\"\r\n");
      out.write("\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t<span class=\"caret\"></span> <span class=\"sr-only\">Toggle\r\n");
      out.write("\t\t\t\tDropdown</span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t<li><a href=\"#\">Edit Account</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Help</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">About</a></li>\r\n");
      out.write("\t\t\t<li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Exit</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</nav> </nav>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"main\" class=\"container\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<h3 class=\"page-header\">Delete Property</h3>\r\n");
      out.write("<!-- Formulario para exclusão de property -->\r\n");
      out.write("<form action=\"Propertydelete.do\" method=\"post\">\r\n");
      out.write("<!-- area de campos do form -->\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"form-group col-md-12\">\r\n");
      out.write("<label for=\"nome\">Nome</label>\r\n");
      out.write("<input type=\"text\" class=\"form-control\" name=\"stringName\" id=\"stringName\"\r\n");
      out.write("required maxlength=\"100\" placeholder=\"nom \">\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"form-group col-md-6\">\r\n");
      out.write("<label for=\"fone\">Andar</label>\r\n");
      out.write("<input type=\"tel\" class=\"form-control\" name=\"stringAndar\" id=\"stringAndar\"\r\n");
      out.write("maxlength=\"15\" pattern=\"(?:\\(\\d{2}\\)|\\d{2})[- ]?\\d{5}[- ]?\\d{4}\" placeholder=\"\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<hr />\r\n");
      out.write("<div id=\"actions\" class=\"row\">\r\n");
      out.write("<div class=\"col-md-12\">\r\n");
      out.write("<button type=\"submit\" class=\"btn btn-primary\" name=\"acao\"\r\n");
      out.write("value=\"Criar\">Salvar</button>\r\n");
      out.write("<a href=\"index.html\" class=\"btn btn-default\">Cancelar</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\t\thref=\"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
